"""Render AmneziaWG config text for the shared server identity and for clients.

Every node gets the *same* server config (same keys, same peers), which is what
lets one client hand-shake with any node under a single endpoint. The server
config is MTU-safe by construction: MTU is pinned low and PostUp clamps TCP MSS
to the path, so large packets never black-hole the way they do on resellers
that quietly deliver a sub-1500 path.
"""

from __future__ import annotations

import ipaddress

from .models import Client, FleetConfig

def _post_up(port: int) -> str:
    """Open the listen port in INPUT (nodes with a default-DROP policy would
    otherwise silently eat every handshake), then set up NAT, forwarding and an
    MSS clamp keyed off the node's real default-route interface."""
    return (
        f"iptables -I INPUT -p udp --dport {port} -j ACCEPT; "
        "DEV=$(ip route show default | awk '{print $5; exit}'); "
        "iptables -I FORWARD -i %i -j ACCEPT; "
        "iptables -I FORWARD -o %i -j ACCEPT; "
        "iptables -t nat -A POSTROUTING -o $DEV -j MASQUERADE; "
        "iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN "
        "-j TCPMSS --clamp-mss-to-pmtu"
    )


def _post_down(port: int) -> str:
    return _post_up(port).replace("-I ", "-D ").replace("-A ", "-D ")


def server_tunnel_address(cfg: FleetConfig) -> str:
    """The gateway address inside the tunnel, e.g. 10.8.0.1 for 10.8.0.0/24."""
    net = ipaddress.ip_network(cfg.subnet, strict=False)
    return f"{next(net.hosts())}/{net.prefixlen}"


def client_endpoint_port(cfg: FleetConfig, client: Client) -> int:
    """The port in the client's endpoint. A pinned client carries their personal
    port (their identity on the shared domain); a legacy client uses the plain
    listen port and simply follows the domain record."""
    return client.port or cfg.listen_port


STEER_SCRIPT_PATH = "/etc/amnezia/amneziawg/steer.sh"


def render_steering_script(cfg: FleetConfig, host: str, targets: dict[int, str]) -> str:
    """The per-node iptables script that implements client pinning.

    `targets` maps a client's personal port to the node that should carry them
    right now (their pin, or a failover stand-in while the pin is down). The
    node this script runs on answers its own clients locally (REDIRECT to the
    real listen port) and relays every other client's UDP to their node
    (DNAT + MASQUERADE, so replies come back through the same path). Identity
    lives in the port, so this works no matter which node DNS hands a client —
    their traffic always egresses from one IP and IP-bound sessions survive
    reconnects. Rules live in dedicated chains rebuilt atomically per apply, so
    re-running is idempotent and never stacks duplicates."""
    lines = [
        "#!/bin/sh",
        "# generated by awg-fleet; applied by the controller and on awg0 PostUp",
        "iptables -t nat -N AWGF_STEER 2>/dev/null || true",
        "iptables -t nat -F AWGF_STEER",
        "iptables -t nat -C PREROUTING -j AWGF_STEER 2>/dev/null || iptables -t nat -I PREROUTING -j AWGF_STEER",
        "iptables -t nat -N AWGF_STEER_POST 2>/dev/null || true",
        "iptables -t nat -F AWGF_STEER_POST",
        "iptables -t nat -C POSTROUTING -j AWGF_STEER_POST 2>/dev/null || iptables -t nat -I POSTROUTING -j AWGF_STEER_POST",
        "iptables -N AWGF_STEER_FWD 2>/dev/null || true",
        "iptables -F AWGF_STEER_FWD",
        "iptables -C FORWARD -j AWGF_STEER_FWD 2>/dev/null || iptables -I FORWARD -j AWGF_STEER_FWD",
        "iptables -A AWGF_STEER_FWD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
    ]
    for port in sorted(targets):
        target = targets[port]
        if target == host:
            lines.append(
                f"iptables -t nat -A AWGF_STEER -p udp --dport {port} "
                f"-j REDIRECT --to-ports {cfg.listen_port}"
            )
        else:
            lines += [
                f"iptables -t nat -A AWGF_STEER -p udp --dport {port} "
                f"-j DNAT --to-destination {target}:{port}",
                f"iptables -t nat -A AWGF_STEER_POST -p udp -d {target} --dport {port} -j MASQUERADE",
                f"iptables -A AWGF_STEER_FWD -p udp -d {target} --dport {port} -j ACCEPT",
            ]
    return "\n".join(lines) + "\n"


def render_steering_teardown() -> str:
    """Drop the steering chains (used when a node leaves the fleet)."""
    out = []
    for table, chain in (
        ("nat", "AWGF_STEER"),
        ("nat", "AWGF_STEER_POST"),
        ("filter", "AWGF_STEER_FWD"),
    ):
        hook = {"AWGF_STEER": "PREROUTING", "AWGF_STEER_POST": "POSTROUTING", "AWGF_STEER_FWD": "FORWARD"}[chain]
        t = f"-t {table} " if table == "nat" else ""
        out += [
            f"iptables {t}-D {hook} -j {chain} 2>/dev/null || true",
            f"iptables {t}-F {chain} 2>/dev/null || true",
            f"iptables {t}-X {chain} 2>/dev/null || true",
        ]
    return "; ".join(out)


_OBF_ORDER = (
    "Jc", "Jmin", "Jmax", "S1", "S2", "S3", "S4",
    "H1", "H2", "H3", "H4", "I1", "I2", "I3", "I4", "I5",
)


def _obfuscation_lines(cfg: FleetConfig) -> list[str]:
    o = cfg.obfuscation
    return [f"{k} = {o[k]}" for k in _OBF_ORDER if k in o]


def render_server_conf(cfg: FleetConfig) -> str:
    lines = [
        "[Interface]",
        f"PrivateKey = {cfg.server_private_key}",
        f"Address = {server_tunnel_address(cfg)}",
        f"ListenPort = {cfg.listen_port}",
        f"MTU = {cfg.mtu}",
        f"PostUp = {_post_up(cfg.listen_port)}",
        # restore client-pinning rules after a reboot (iptables state is not
        # persistent; the interface unit is). No PostDown twin on purpose.
        f"PostUp = [ -f {STEER_SCRIPT_PATH} ] && sh {STEER_SCRIPT_PATH} || true",
        f"PostDown = {_post_down(cfg.listen_port)}",
        *_obfuscation_lines(cfg),
    ]
    for c in cfg.clients:
        lines += ["", "[Peer]", f"PublicKey = {c.public_key}"]
        if c.preshared_key:
            lines.append(f"PresharedKey = {c.preshared_key}")
        lines.append(f"AllowedIPs = {c.address}")
    return "\n".join(lines) + "\n"


def render_client_conf(cfg: FleetConfig, client: Client) -> str:
    """A client config whose Endpoint is the fleet domain, not any single node."""
    lines = [
        "[Interface]",
        f"PrivateKey = {client.private_key}",
        f"Address = {client.address}",
        f"DNS = {cfg.dns}",
        f"MTU = {cfg.mtu}",
        *_obfuscation_lines(cfg),
        "",
        "[Peer]",
        f"PublicKey = {cfg.server_public_key}",
    ]
    if client.preshared_key:
        lines.append(f"PresharedKey = {client.preshared_key}")
    lines += [
        "AllowedIPs = 0.0.0.0/0, ::/0",
        f"Endpoint = {cfg.domain}:{client_endpoint_port(cfg, client)}",
        "PersistentKeepalive = 25",
    ]
    return "\n".join(lines) + "\n"
